# Generated by Django 5.1.1 on 2024-09-17 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bags', '0002_alter_orderitem_total_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='total_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
