# Generated by Django 5.1.1 on 2024-09-08 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brand',
            name='category',
            field=models.ManyToManyField(to='product.category'),
        ),
    ]
