# Generated by Django 5.1.1 on 2024-09-14 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_alter_product_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='mapping_category',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
